### ISSUE TITLE
emotiv-bci

### ISSUE THREAD

**Issue by xiangjiannini** [Emotiv/opensoundcontrol#11]
[EmotivOSCPython.py],can that code get data from emotiv-bci?

**Comment by hoangphamemotiv** [comment]
Hi @xiangjiannini . did you mean about: https://github.com/Emotiv/opensoundcontrol/tree/master/examples/python ?
yes, it can help to do that.

**Comment by xiangjiannini** [comment]
Can we store the results returned by these algorithms locally?

**Comment by hoangphamemotiv** [comment]
@xiangjiannini . can you tell me more detail on your issue?

**Comment by xiangjiannini** [comment]
tomorrow,after I ask my boss and get his&nbsp;requirements ,I will tell you more details.



---Original---
From: "Pham ***@***.***&gt;
Date: Wed, Sep 7, 2022 18:02 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Emotiv/opensoundcontrol] emotiv-bci (Issue #11)




 
@xiangjiannini . can you tell me more detail on your issue?
