### ISSUE TITLE
Error assigning OSC address for performance metrics (att & eng) 

### ISSUE THREAD

**Issue by mauroLab** [Emotiv/opensoundcontrol#13]
There is an error when assigning the OSC address with which information is sent for performance metrics.
When I try to give an OSC address to "attention" y automatically changes the address of "engagement" as well.
If I do it the other way around, "engagement" sets the address for "attention".

The problem occurs only with these two variables, the rest are fine.

Cheers

**Comment by tanphamv** [comment]
hi, after update to last version, you need to creat a new preset and add the mapping again
![image](https://github.com/Emotiv/opensoundcontrol/assets/144306052/4427e708-5596-40b0-b2d4-94811ebaab52)

**Comment by hoangphamemotiv** [comment]
Hi @mauroLab 
We fixed this issue in the newest EmotivBCI and update it into Emotiv OSC repo. https://github.com/Emotiv/opensoundcontrol
