### ISSUE TITLE
OSC Data not sending to other Apps

### ISSUE THREAD

**Issue by DSISoundDesigns** [Emotiv/opensoundcontrol#15]
Hi,
So my issue is that, after updating to the newest versions of all the Emotiv Apps (3.7.1.363), I cannot get any OSC messages to be received by any other outside application via local host or a separate IP. I am currently trying to send the OSC data from BCI-OSC to MaxMSP and/or VCVRack. I have updated on both MacOS and WinX and experience the same issue on both systems. 

- side note: when changing values on the Attention metric, like the OCS message itself, any changes do not stay and revert to 0's and blanks.

**Comment by tanphamv** [comment]
> Hi, So my issue is that, after updating to the newest versions of all the Emotiv Apps (3.7.1.363), I cannot get any OSC messages to be received by any other outside application via local host or a separate IP. I am currently trying to send the OSC data from BCI-OSC to MaxMSP and/or VCVRack. I have updated on both MacOS and WinX and experience the same issue on both systems.
> 
> * side note: when changing values on the Attention metric, like the OCS message itself, any changes do not stay and revert to 0's and blanks.

hi [DSISoundDesigns](https://github.com/DSISoundDesigns), after update to last version, you need to creat a new preset and add the mapping again

**Comment by DSISoundDesigns** [comment]
This is not the issue.....
I used the simulated device and still did not get any OSC to output... No
OSC data is being sent from the BCI OSC application at all...

**Comment by hoangphamemotiv** [comment]
@DSISoundDesigns 
![image](https://github.com/Emotiv/opensoundcontrol/assets/13273932/249b1e41-e7c8-489a-950c-496802cb8428)

i just checked again on Max 8. seem It works fine. Can you do some steps: 
- Make sure you update the latest Cortex and Emotiv OSC version. 
- Make sure you created a new Preset which fixed the Attention detection with mapping: /met/att
- Update code from Emotiv OSC repo: https://github.com/Emotiv/opensoundcontrol/tree/master
Tell me if you still get the issue then please send me a capture image that you set up for MAXMSP

**Comment by DSISoundDesigns** [comment]
I have followed the steps above. It seems I am up to date on all apps. 
I am still encountering these things:
- I cant create a new preset, that button is greyed out for me and does nothing when I click.
- OSC is not being seen by Max on my machine 
In this screenshot, I have a simulated device active and the BCIOSC app is connected. The Max console is not updating with new messages being printed.
![image_2023-12-01_084602968](https://github.com/Emotiv/opensoundcontrol/assets/100877666/3974431b-7a1f-435f-be55-820fadd2bd4d)

**Comment by DSISoundDesigns** [comment]
The "add preset" button is greyed out on both MacOS and Windows for me as well

**Comment by DSISoundDesigns** [comment]
I was able to create a new preset today. But, I still have the same problem. There are no OCS messages being sent from the BCIOSC App. With the new preset, I started the simulated headset again and recreated the situation above in Maxmsp and BCIOSC. I am STILL encountering the same issue.

**Comment by hoangphamemotiv** [comment]
@DSISoundDesigns . 
i understand you installed: CNMAT Externals ?
https://github.com/Emotiv/opensoundcontrol/tree/master/examples/Max

Can you capture a video to show your case more clear?

**Comment by DSISoundDesigns** [comment]
Yes, I have the CNMAT externals installed.
I will try to upload a screen capture of my issue here shortly

**Comment by DSISoundDesigns** [comment]
Upon recording my screenshot, my issue has been resolved somehow. 
I can now use BCIOSC and the OSC messages are being sent out.
If this happens again, I will post back in this thread
