### ISSUE TITLE
Arduino code 

### ISSUE THREAD

**Issue by Doody02** [Emotiv/opensoundcontrol#3]
Greetings , I've tried to get the code running for EmotivOSC_Adruino.ino but it has many errors like the #include and declaring the void . 
please advise ....

thank you so much for the help ....
PS : I am trying to run the code in Arduino because I want to move a car module and I bought the Emotive BCI OSC but there is no connection between the sensor and the car ....

thanks in Advanced ...

**Comment by hoangphamemotiv** [comment]
hi @Doody02 . 
i updated document for the Arduino example: https://github.com/Emotiv/opensoundcontrol/tree/master/examples/EmotivOSC_Adruino
About your project, what detections do we want to control your car? at the first, you should besure Emotiv BCI sent data to your Arduino successful. can you share me your code?

**Comment by Doody02** [comment]
hi @hoangphamemotiv .
I used the codes after the update and still got the same problem , I know how to send the data from BCI but I dont know how it get to arduino . 

i want to move the car these direction ( forward - back word - Right and Left ) , by using the emotive epoc x sensor .

**Comment by hoangphamemotiv** [comment]
@Doody02 
did you upload success the code into your board?
what is your Arduino board version? do it connect to LAN via a Ethernet cable or via Wifi?
for debuging, you can use a serial port to send back Emotiv detection value to your BCI installed machine and display result in Serial Monitor. so you can know the board received BCI data successfull

**Comment by Doody02** [comment]
Greetings,

Arduino upload : success
Arduino type : uno
It does not connect to LAN via Ethernet or wifi ( how do I do this)  .

As for debugg I use USB, but how to send and receive data via USB because I want to move the car remotly.

The main problem right now is how to connect HC_05 to the sensor ( I uploaded thr codes but still it won't connect).

Please Advise..
Thanks I'm advanced...

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by hoangphamemotiv** [comment]
@Doody02 
i understood your issue. 
you need connect your board to LAN (Ethernet or wifi) to receive BCI data in real time. Arduino don't work alone, it need BCI data to control your car. 
to connect Arduino to LAN you need an extral board as ESP8266 Node MCU board. 
i captured a image in: https://github.com/Emotiv/opensoundcontrol/tree/master/examples/EmotivOSC_Adruino
about debuging via serial port, it just to make your arduino board can receive BCI data success: https://www.instructables.com/HOW-TO-use-the-ARDUINO-SERIAL-MONITOR/
after every thing done, you don't need to connect your board with serial port.

**Comment by Doody02** [comment]
Greetings,

Will use the bridge now,  may I know how to use the wifi connection ( the set up)  .

Thanks in advanced...

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by Doody02** [comment]
Greetings ; would you please help me out . I tried to use ESP8266 wifi but when i downloaded the library and the code the compile was fine but I always get the error message ( Arduino: 1.8.13 (Windows 10), Board: "Generic ESP8266 Module, 80 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), dtr (aka nodemcu), 26 MHz, 40MHz, DOUT (compatible), 1MB (FS:64KB OTA:~470KB), 2, nonos-sdk 2.2.1+100 (190703), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

Executable segment sizes:

IROM   : 282052          - code in flash         (default or ICACHE_FLASH_ATTR) 

IRAM   : 27672   / 32768 - code in IRAM          (ICACHE_RAM_ATTR, ISRs...) 

DATA   : 1260  )         - initialized variables (global, static) in RAM/HEAP 

RODATA : 1012  ) / 81920 - constants             (global, static) in RAM/HEAP 

BSS    : 25336 )         - zeroed variables      (global, static) in RAM/HEAP 

Sketch uses 311996 bytes (32%) of program storage space. Maximum is 958448 bytes.

Global variables use 27608 bytes (33%) of dynamic memory, leaving 54312 bytes for local variables. Maximum is 81920 bytes.

esptool.py v2.8

Serial port COM3

Connecting........_____....._____....._____....._____....._____....._____....._____

Traceback (most recent call last):

  File "C:\Users\96653\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4/tools/upload.py", line 65, in <module>

    esptool.main(cmdline)

  File "C:/Users/96653/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/tools/esptool\esptool.py", line 2890, in main

    esp.connect(args.before)

  File "C:/Users/96653/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/tools/esptool\esptool.py", line 483, in connect

    raise FatalError('Failed to connect to %s: %s' % (self.CHIP_NAME, last_error))

esptool.FatalError: Failed to connect to ESP8266: Timed out waiting for packet header

esptool.FatalError: Failed to connect to ESP8266: Timed out waiting for packet header





This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.


thanks in advanced.........

**Comment by hoangphamemotiv** [comment]
@Doody02 
i think you can test with simple code to connect your board to wifi first. after every work fine we can go to next steps.

**Comment by Doody02** [comment]
@hoangphamemotiv hello , I have a question please , when am done with the code via ESP8266 Node MCU boards ( Ethernet ) how will the object move or run when i disconnect it from the PC , meaning when am done compiling and uploading through arduino  uno , how will it move and thanks .....

**Comment by hoangphamemotiv** [comment]
@Doody02 . 
You may do steps in: https://github.com/Emotiv/opensoundcontrol/tree/master/examples/EmotivOSC_Adruino
You will wearing an Emotiv headset, connect it with EmotivBCI. EmotivBCI will send detection values, Motion values via wifi to your Arduino board and control your car.

**Comment by Doody02** [comment]
@hoangphamemotiv I checked the link and it does not have anything with arduino connection . 

Just wanna know the coding i should use and what example on arduino uno , thanks in advanced ....

**Comment by hoangphamemotiv** [comment]
seem this issue related to: https://github.com/Emotiv/opensoundcontrol/issues/5

**Comment by Doody02** [comment]
Greetings,  I would like an assistance please.

I have uploaded the Ethernet code on arduino MCU so I can transmit the data via wifi just like Mr. Pham hoang told me because he explain to me that both Ethernet and WiFi run with the same code just make sure that wifi is working.

I really thank him for reply.

The problem is arduino seems can't run wifi and uploaded code at same time so is there any other way to use WiFi to transmit the data to arduino via wifi,  maybe am missing something please let me know.


Even if raspberry Pi is the solution I do have it, would please be kind and guid me .


I hope to run it in both arduino and raspberry Pi.


Thanks in advanced ....

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by hoangphamemotiv** [comment]
@Doody02 
you need to connect your Arduino to PC via serial port and upload your Wifi code at the first, like the way you did with Ethernet code.

**Comment by Doody02** [comment]
Greetings,  yep I did that and it didn't work here is my code.

/*---------------------------------------------------------------------------------------------

  Open Sound Control (OSC) library for the ESP8266/ESP32

  Example for receiving open sound control (OSC) messages on the ESP8266/ESP32
  Send integers '0' or '1' to the address "/led" to turn on/off the built-in LED of the esp8266.

  This example code is in the public domain.

--------------------------------------------------------------------------------------------- */
#include <ArduinoOSCWiFi.h>
#ifdef ESP8266
#include <ESP8266WiFi.h>
#else
#include <WiFi.h>
#endif
#include <WiFiUdp.h>
#include <OSCMessage.h>
#include <OSCBundle.h>
#define LED1 2 //red
#define LED2 3 //red
#define LED3 4 //red
#define LED4 5 //green
#define LED5 6 //yellow
#include <OSCData.h>

byte mac[] = { 0xDE, 0xAD, 0xBE, 0xEF, 0xFE, 0xED }; // NOTE: Alternatively, you can assign a fixed IP to configure your Ethernet shield.
byte ip[] = { 192, 168, 43, 233 };
int serverPort = 8500; // Emotiv BCI out port


char ssid[] = "Velvet-Room";          // your network SSID (name)
char pass[] = "0555543946";                    // your network password


// A UDP instance to let us send and receive packets over UDP
WiFiUDP Udp;
const IPAddress outIp(192,168,43,233);        // remote IP (not needed for receive)
//const unsigned int outPort = 8500;          // remote port (not needed for receive)
const unsigned int localPort = 8500;        // local port to listen for UDP packets (here's where we send the packets)



void setup() {

  Serial.begin(9600);
    Serial.println("Emotiv BCI OSC test");


  // Connect to WiFi network
  Serial.println();
  Serial.println();
  Serial.print("Connecting to ");
  Serial.println(ssid);
  WiFi.begin(ssid, pass);

  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("");

  Serial.println("WiFi connected");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());

  Serial.println("Starting UDP");
  Udp.begin(localPort);
  Serial.print("Local port: ");
#ifdef ESP32
  Serial.println(localPort);
#else
  Serial.println(Udp.localPort());
  Serial.println();
  Udp.begin(serverPort);
   pinMode(LED1, OUTPUT);
  pinMode(LED2, OUTPUT);
  pinMode(LED3, OUTPUT);
  pinMode(LED4, OUTPUT);
  pinMode(LED5, OUTPUT);

#endif
}






void loop() {
 /* OSCMessage msg;
  int size = Udp.parsePacket();

  if (size > 0) {
    while (size--) {
      msg.fill(Udp.read());
    }
    if (!msg.hasError()) {
    } else {
      Serial.print("error: ");
    }
  }*/

  //process received data from Emotiv BCI
  OSCMsgReceive();
}
void OSCMsgReceive() {
  int size = Udp.parsePacket();
  if(size > 1) {
    OSCBundle bundleIN;
    while(size--)
      bundleIN.fill(Udp.read());
      if(!bundleIN.hasError()){
        bundleIN.route("/fac/eyeAct", processFEEyeAct);  // Facial_Expressions
         bundleIN.route("/fac/uAct",   processFEUAct);    // Facial_Expressions
         bundleIN.route("/fac/lAct",   processFELAct);    // Facial_Expressions
        bundleIN.route("/com", processMC); // Mental_Commands
   //     bundleIN.route("/met", processPM); // Performance_Metrics
    }
  }
}
 void processFEEyeAct(OSCMessage &msg, int addrOffset) {
  if(msg.match("/lookL", addrOffset)) {
    Serial.println("FE - Look Left");
  } else if(msg.match("/lookR", addrOffset)) {
    Serial.println("FE - Look Right");
  } else if(msg.match("/blink", addrOffset)) {
    Serial.println("FE - Blink");
  } else if(msg.match("/winkL", addrOffset)) {
    Serial.println("FE - Wink Left");
     digitalWrite(LED4, HIGH);
      delay(25);
      digitalWrite(LED4, LOW);
  } else if(msg.match("/winkR", addrOffset)) {
    Serial.println("FE - Wink Right");
  }
}


void processFEUAct(OSCMessage &msg, int addrOffset) {
  if(msg.match("/frown", addrOffset)) {
    if(msg.isFloat(0)) {
      Serial.print("FE - Frown: ");
    }
  } else if(msg.match("/surprise", addrOffset)) {
    Serial.print("FE - Surprise: ");
  }

  if(msg.isFloat(0)) {
    float value = msg.getFloat(0);
    Serial.println(value);
  }
}


void processFELAct(OSCMessage &msg, int addrOffset)
{
    if(msg.match("/Left", addrOffset))
    {
      digitalWrite(LED2, HIGH);
      Serial.print("FE - Left: ");
    }
    /*else if(msg.match("/Push", addrOffset))
    {
      digitalWrite(LED3, HIGH);
      Serial.print("FE - Push: ");
    }*/
    else if(msg.match("/smile", addrOffset))
    {
      digitalWrite(LED2, HIGH);
      delay(25);
      digitalWrite(LED2, LOW);
      Serial.print("FE - Smile: ");
    }
    else if(msg.match("/Furrow Brows", addrOffset))
    {
      digitalWrite(LED4, HIGH);
      delay(25);
      digitalWrite(LED4, LOW);
      Serial.print("FE - Furrow Brows: ");
    }
      else if(msg.match("/winkL", addrOffset)) {
    Serial.println("FE - Wink Left");
     digitalWrite(LED3, HIGH);
      delay(25);
      digitalWrite(LED3, LOW);
    }
  /*  else if(msg.match("/smirkLeft", addrOffset))
    {
      Serial.print("FE - Smirk Left: ");
    }
    else if(msg.match("/smirkRight", addrOffset))
    {
      Serial.print("FE - Smirk Right: ");
    }
*/
  if(msg.isFloat(0))
  {
    float value = msg.getFloat(0);
    Serial.println(value);
  }
}
/*
void processMC(OSCMessage &msg, int addrOffset) {
if(msg.match("/neutral", addrOffset)) {
Serial.print("MC - Neutral: ");
digitalWrite(LM1, LOW);
digitalWrite(LM2, LOW);
} else if(msg.match("/push", addrOffset)) {
Serial.print("MC - Push: ");
digitalWrite(LM1, HIGH);
} else if(msg.match("/pull", addrOffset)) {
Serial.print("MC - Pull: ");
digitalWrite(LM2, HIGH);
}
*/
void processMC(OSCMessage &msg, int addrOffset) {
  if(msg.match("/neutral", addrOffset)) {
    digitalWrite(LED1, HIGH);
     delay(25);
      digitalWrite(LED1, LOW);
    Serial.print("MC - Push: ");
  } else if(msg.match("/push", addrOffset)) {
    digitalWrite(LED4, HIGH);
     delay(25);
      digitalWrite(LED4, LOW);
    Serial.print("MC - Push: ");
  }
}
/* } else if(msg.match("/pull", addrOffset)) {
    Serial.print("MC - Pull: ");
  } else if(msg.match("/left", addrOffset)) {
  //  digitalWrite(LED2, HIGH);
    Serial.print("MC - Left: ");
  } else if(msg.match("/Smile", addrOffset)) {
    //digitalWrite(LED3, HIGH);
    Serial. print("MC - Right: ");

  else if(msg.match("/lift", addrOffset)) {

     digitalWrite(LED4, HIGH);
      delay(25);
      digitalWrite(LED4, LOW);
      Serial.print("MC - lift: ");
  }
}

 /* } else if(msg.match("/drop", addrOffset)) {
    Serial.print("MC - drop: ");
  } else if(msg.match("/rotateLeft", addrOffset)) {
    Serial.print("MC - rotateLeft: ");
  } else if(msg.match("/rotateRight", addrOffset)) {
    Serial.print("MC - rotateRight: ");
  } else if(msg.match("/rotateClockwise", addrOffset)) {
    Serial.print("MC - rotateClockwise: ");
  } else if(msg.match("/rotateCounterClockwise", addrOffset)) {
    Serial.print("MC - rotateCounterClockwise: ");
  } else if(msg.match("/rotateForwards", addrOffset)) {
    Serial.print("MC - rotateForwards: ");
  } else if(msg.match("/rotateReverse", addrOffset)) {
    Serial.print("MC - rotateReverse: ");
  } else if(msg.match("/disappear", addrOffset)) {
    Serial.print("MC - disappear: ");
  }

  if(msg.isFloat(0)) {
    float value = msg.getFloat(0);
    Serial.println(value);
  }
}
}
/*
void processPM(OSCMessage &msg, int addrOffset) {
  if(msg.match("/foc", addrOffset)) {
    Serial.print("PM - focus: ");
  } else if(msg.match("/int", addrOffset)) {
    Serial.print("PM - interest: ");
  } else if(msg.match("/rel", addrOffset)) {
    Serial.print("PM - relaxation: ");
  } else if(msg.match("/str", addrOffset)) {
    Serial.print("PM - stress: ");
  } else if(msg.match("/exc", addrOffset)) {
    Serial.print("PM - excitement: ");
  } else if(msg.match("/eng", addrOffset)) {
    Serial.print("PM - engagement: ");
  }
//  else if(msg.match("/cognitiveStress", addrOffset)) {
//    Serial.print("PM - cognitiveStress: ");
//  }
//  else if(msg.match("/visualAttention", addrOffset)) {
//    Serial.print("PM - visualAttention: ");
//  }
//  else if(msg.match("/auditoryAttention", addrOffset)) {
//    Serial.print("PM - auditoryAttention: ");
//  }

  if(msg.isFloat(0)) {
    float value = msg.getFloat(0);
    Serial.println(value);
  }
}*/

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
