### ISSUE TITLE
Unity Example

### ISSUE THREAD

**Issue by Doody02** [Emotiv/opensoundcontrol#6]
Greetings , am trying to move the cube from the example on unity but it keep telling me that unity cannot build a server on 8500 port . 
I just wanna move the cube on unity would you please kindly help me . 
![unityPort Error](https://user-images.githubusercontent.com/34331105/112426350-df648280-8d48-11eb-95dd-823905d16773.PNG)

**Comment by hoangphamemotiv** [comment]
@Doody02 . can you use other port number? seem, 8500 is used by other app or not closed from old one.

**Comment by Doody02** [comment]
Already did , still same problem

**Comment by hoangphamemotiv** [comment]
@Doody02 . 
you missed steps of running BCI app with OSC feature. 
you can see steps in: https://www.youtube.com/watch?v=bWdHdnQbby4
and document: https://github.com/Emotiv/opensoundcontrol/tree/master/examples/Unity
