### ISSUE TITLE
BCI-OSC code 

### ISSUE THREAD

**Issue by Doody02** [Emotiv/opensoundcontrol#7]
Greetings , I've done the experiment on controlling LED light by using Arduino uno and emotive BCI-OSC Ethernet connection and it was a success , I would like to do the same but with Wi-Fi so I got the Arduino mcu and got all the connection right but would please tell me if my code is wrong or is it something am missing …

PS : the BCI window is blurr because am not connecting the sensor right now .

the code ..

#include <OSCBoards.h>
#include <OSCBundle.h>
#include <OSCData.h>
#include <OSCMatch.h>
#include <OSCMessage.h>
#include <OSCTiming.h>
#include <SLIPEncodedSerial.h>
#include <SLIPEncodedUSBSerial.h>
#include <SPI.h>
#include <WiFi.h>
#include <WiFiUdp.h>
#include <ESP8266WiFi.h>

char ssid[] = "Velvet-Room";
char pass[] = "0555543946";

#define LED1 2 //red
#define LED2 3 //red
#define LED3 4 //red
#define LED4 5 //green
#define LED5 6 //yellow

const IPAddress outIp(192,168,43,233);
const unsigned int outport = 9999;
const unsigned int localPort = 8500 ; 

// you can find this written on the board of some Arduino Ethernets or shields
char mac[] = { 0xDE, 0xAD, 0xBE, 0xEF, 0xFE, 0xED }; // NOTE: Alternatively, you can assign a fixed IP to configure your Ethernet shield.
byte ip[] = { 192, 168, 43, 233 };
int serverPort = 8500; // Emotiv BCI out port
WiFiUDP Udp;

void setup() {
  // put your setup code here, to run once:
Serial.begin(9600); //9600 for a "normal" Arduino board (Uno for example). 115200 for a Teensy ++2 
  Serial.println("Emotiv BCI OSC test");
  pinMode(LED1, OUTPUT);
  pinMode(LED2, OUTPUT);
  pinMode(LED3, OUTPUT);
  pinMode(LED4, OUTPUT);
  pinMode(LED5, OUTPUT);

while (!Serial) {
    ; // wait for serial port to connect. Needed for native USB port only
  }

  Serial.print("Attempting to connect to SSID: ");
  Serial.print(ssid);

  // Attempt to connect to WiFi network:
  while (WiFi.status() != WL_CONNECTED) {
    Serial.print(".");
    // Connect to WPA/WPA2 network. Change this line if using open or WEP  network:
    // Wait 5 seconds for connection:
    delay(5000);
  }

  Serial.println("");
  Serial.println("WiFi connected");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());   //You can get IP address assigned to ESP
}

 

void loop() {
  // put your main code here, to run repeatedly:
 //process received data from Emotiv BCI
 if (WiFi.begin(mac) == 0) {
      Serial.println("Failed to configure Wifi using DHCP");
      while(true);
}

//   Serial.print("Arduino IP address: ");
  for (byte thisByte = 1; thisByte < 4; thisByte++) {
    // print the value of each byte of the IP address:
    Serial.print(".");
  }
  Serial.println();
  //Udp.begin(serverport);
}
  
//  OSCMsgReceive();

void OSCMsgReceive() {
  int size = Udp.parsePacket();  
  if(size > 1) {    
    OSCBundle bundleIN;
    while(size--)
      bundleIN.fill(Udp.read());
      if(!bundleIN.hasError()){
        bundleIN.route("/fac/eyeAct", processFEEyeAct);  // Facial_Expressions
         bundleIN.route("/fac/uAct",   processFEUAct);    // Facial_Expressions
         bundleIN.route("/fac/lAct",   processFELAct);    // Facial_Expressions
        bundleIN.route("/com", processMC); // Mental_Commands
   //     bundleIN.route("/met", processPM); // Performance_Metrics
    }
  }
}
 void processFEEyeAct(OSCMessage &msg, int addrOffset) {
  if(msg.match("/lookL", addrOffset)) {
    Serial.println("FE - Look Left");
  } else if(msg.match("/lookR", addrOffset)) {
    Serial.println("FE - Look Right");
  } else if(msg.match("/blink", addrOffset)) {
    Serial.println("FE - Blink");
  } else if(msg.match("/winkL", addrOffset)) {
    Serial.println("FE - Wink Left");
     digitalWrite(LED4, HIGH);
      delay(25);
      digitalWrite(LED4, LOW);
  } else if(msg.match("/winkR", addrOffset)) {
    Serial.println("FE - Wink Right");
  }
}

void processFEUAct(OSCMessage &msg, int addrOffset) {
  if(msg.match("/frown", addrOffset)) {
    if(msg.isFloat(0)) {
      Serial.print("FE - Frown: ");
    }
  } else if(msg.match("/surprise", addrOffset)) {
    Serial.print("FE - Surprise: ");
  }

  if(msg.isFloat(0)) {
    float value = msg.getFloat(0);
    Serial.println(value);
  }
}

void processFELAct(OSCMessage &msg, int addrOffset)
{
    if(msg.match("/Left", addrOffset))
    {
      digitalWrite(LED2, HIGH);
      Serial.print("FE - Left: ");
    } 
    /*else if(msg.match("/Push", addrOffset))
    {
      digitalWrite(LED3, HIGH);
      Serial.print("FE - Push: ");
    }*/
    else if(msg.match("/smile", addrOffset))
    {
      digitalWrite(LED2, HIGH);
      delay(25);
      digitalWrite(LED2, LOW);
      Serial.print("FE - Smile: ");
    }
    else if(msg.match("/Furrow Brows", addrOffset))
    {
      digitalWrite(LED4, HIGH);
      delay(25);
      digitalWrite(LED4, LOW);
      Serial.print("FE - Furrow Brows: ");
    }
      else if(msg.match("/winkL", addrOffset)) {
    Serial.println("FE - Wink Left");
     digitalWrite(LED3, HIGH);
      delay(25);
      digitalWrite(LED3, LOW);
    }
  /*  else if(msg.match("/smirkLeft", addrOffset))
    {
      Serial.print("FE - Smirk Left: ");
    } 
    else if(msg.match("/smirkRight", addrOffset))
    {
      Serial.print("FE - Smirk Right: ");
    }
*/
  if(msg.isFloat(0))
  {
    float value = msg.getFloat(0);
    Serial.println(value);
  }
}
/*
void processMC(OSCMessage &msg, int addrOffset) {
if(msg.match("/neutral", addrOffset)) {
Serial.print("MC - Neutral: ");
digitalWrite(LM1, LOW);
digitalWrite(LM2, LOW);
} else if(msg.match("/push", addrOffset)) {
Serial.print("MC - Push: ");
digitalWrite(LM1, HIGH);
} else if(msg.match("/pull", addrOffset)) {
Serial.print("MC - Pull: ");
digitalWrite(LM2, HIGH);
}
*/
void processMC(OSCMessage &msg, int addrOffset) {  
  if(msg.match("/neutral", addrOffset)) {
    digitalWrite(LED1, HIGH);
     delay(25);
      digitalWrite(LED1, LOW);
    Serial.print("MC - Push: ");
  } else if(msg.match("/push", addrOffset)) {
    digitalWrite(LED4, HIGH);
     delay(25);
      digitalWrite(LED4, LOW);
    Serial.print("MC - Push: ");
  }
}
/* } else if(msg.match("/pull", addrOffset)) {
    Serial.print("MC - Pull: ");
  } else if(msg.match("/left", addrOffset)) {
  //  digitalWrite(LED2, HIGH);
    Serial.print("MC - Left: ");
  } else if(msg.match("/Smile", addrOffset)) {
    //digitalWrite(LED3, HIGH);
    Serial. print("MC - Right: ");
  
  else if(msg.match("/lift", addrOffset)) {
    
     digitalWrite(LED4, HIGH);
      delay(25);
      digitalWrite(LED4, LOW);
      Serial.print("MC - lift: ");
  }
}
  
 /* } else if(msg.match("/drop", addrOffset)) {
    Serial.print("MC - drop: ");
  } else if(msg.match("/rotateLeft", addrOffset)) {
    Serial.print("MC - rotateLeft: ");
  } else if(msg.match("/rotateRight", addrOffset)) {
    Serial.print("MC - rotateRight: ");
  } else if(msg.match("/rotateClockwise", addrOffset)) {
    Serial.print("MC - rotateClockwise: ");
  } else if(msg.match("/rotateCounterClockwise", addrOffset)) {
    Serial.print("MC - rotateCounterClockwise: ");
  } else if(msg.match("/rotateForwards", addrOffset)) {
    Serial.print("MC - rotateForwards: ");
  } else if(msg.match("/rotateReverse", addrOffset)) {
    Serial.print("MC - rotateReverse: ");
  } else if(msg.match("/disappear", addrOffset)) {
    Serial.print("MC - disappear: ");
  }

  if(msg.isFloat(0)) {
    float value = msg.getFloat(0);
    Serial.println(value);
  }
}
}
/*
void processPM(OSCMessage &msg, int addrOffset) {
  if(msg.match("/foc", addrOffset)) {
    Serial.print("PM - focus: ");
  } else if(msg.match("/int", addrOffset)) {
    Serial.print("PM - interest: ");
  } else if(msg.match("/rel", addrOffset)) {
    Serial.print("PM - relaxation: ");
  } else if(msg.match("/str", addrOffset)) {
    Serial.print("PM - stress: ");
  } else if(msg.match("/exc", addrOffset)) {
    Serial.print("PM - excitement: ");
  } else if(msg.match("/eng", addrOffset)) {
    Serial.print("PM - engagement: ");
  } 
//  else if(msg.match("/cognitiveStress", addrOffset)) {
//    Serial.print("PM - cognitiveStress: ");
//  }
//  else if(msg.match("/visualAttention", addrOffset)) {
//    Serial.print("PM - visualAttention: ");
//  } 
//  else if(msg.match("/auditoryAttention", addrOffset)) {
//    Serial.print("PM - auditoryAttention: ");
//  }

  if(msg.isFloat(0)) {
    float value = msg.getFloat(0);
    Serial.println(value);
  }
}*/
![mcu](https://user-images.githubusercontent.com/34331105/121190991-3839b680-c874-11eb-87aa-5d2c79135ff8.jpeg)
![Test1](https://user-images.githubusercontent.com/34331105/121191237-7636da80-c874-11eb-9866-9d753812dd20.PNG)

**Comment by hoangphamemotiv** [comment]
hi @Doody02 the code process and extract data from Arduino are the sam for both of Ethernet and wifi connections.  so i think you may get issue with connect your arduino to wifi.

**Comment by Doody02** [comment]
Greetings thank you for reply.

I still have the same problem even if the arduino is connected to wifi,  may I show you the code plz.



/*---------------------------------------------------------------------------------------------

  Open Sound Control (OSC) library for the ESP8266/ESP32

  Example for receiving open sound control (OSC) messages on the ESP8266/ESP32
  Send integers '0' or '1' to the address "/led" to turn on/off the built-in LED of the esp8266.

  This example code is in the public domain.

--------------------------------------------------------------------------------------------- */
#include <ArduinoOSCWiFi.h>
#ifdef ESP8266
#include <ESP8266WiFi.h>
#else
#include <WiFi.h>
#endif
#include <WiFiUdp.h>
#include <OSCMessage.h>
#include <OSCBundle.h>
#define LED1 2 //red
#define LED2 3 //red
#define LED3 4 //red
#define LED4 5 //green
#define LED5 6 //yellow
#include <OSCData.h>

byte mac[] = { 0xDE, 0xAD, 0xBE, 0xEF, 0xFE, 0xED }; // NOTE: Alternatively, you can assign a fixed IP to configure your Ethernet shield.
byte ip[] = { 192, 168, 43, 233 };
int serverPort = 8500; // Emotiv BCI out port


char ssid[] = "Velvet-Room";          // your network SSID (name)
char pass[] = "0555543946";                    // your network password


// A UDP instance to let us send and receive packets over UDP
WiFiUDP Udp;
const IPAddress outIp(192,168,43,233);        // remote IP (not needed for receive)
//const unsigned int outPort = 8500;          // remote port (not needed for receive)
const unsigned int localPort = 8500;        // local port to listen for UDP packets (here's where we send the packets)



void setup() {

  Serial.begin(9600);
    Serial.println("Emotiv BCI OSC test");


  // Connect to WiFi network
  Serial.println();
  Serial.println();
  Serial.print("Connecting to ");
  Serial.println(ssid);
  WiFi.begin(ssid, pass);

  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("");

  Serial.println("WiFi connected");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());

  Serial.println("Starting UDP");
  Udp.begin(localPort);
  Serial.print("Local port: ");
#ifdef ESP32
  Serial.println(localPort);
#else
  Serial.println(Udp.localPort());
  Serial.println();
  Udp.begin(serverPort);
   pinMode(LED1, OUTPUT);
  pinMode(LED2, OUTPUT);
  pinMode(LED3, OUTPUT);
  pinMode(LED4, OUTPUT);
  pinMode(LED5, OUTPUT);

#endif
}






void loop() {
 /* OSCMessage msg;
  int size = Udp.parsePacket();

  if (size > 0) {
    while (size--) {
      msg.fill(Udp.read());
    }
    if (!msg.hasError()) {
    } else {
      Serial.print("error: ");
    }
  }*/

  //process received data from Emotiv BCI
  OSCMsgReceive();
}
void OSCMsgReceive() {
  int size = Udp.parsePacket();
  if(size > 1) {
    OSCBundle bundleIN;
    while(size--)
      bundleIN.fill(Udp.read());
      if(!bundleIN.hasError()){
        bundleIN.route("/fac/eyeAct", processFEEyeAct);  // Facial_Expressions
         bundleIN.route("/fac/uAct",   processFEUAct);    // Facial_Expressions
         bundleIN.route("/fac/lAct",   processFELAct);    // Facial_Expressions
        bundleIN.route("/com", processMC); // Mental_Commands
   //     bundleIN.route("/met", processPM); // Performance_Metrics
    }
  }
}
 void processFEEyeAct(OSCMessage &msg, int addrOffset) {
  if(msg.match("/lookL", addrOffset)) {
    Serial.println("FE - Look Left");
  } else if(msg.match("/lookR", addrOffset)) {
    Serial.println("FE - Look Right");
  } else if(msg.match("/blink", addrOffset)) {
    Serial.println("FE - Blink");
  } else if(msg.match("/winkL", addrOffset)) {
    Serial.println("FE - Wink Left");
     digitalWrite(LED4, HIGH);
      delay(25);
      digitalWrite(LED4, LOW);
  } else if(msg.match("/winkR", addrOffset)) {
    Serial.println("FE - Wink Right");
  }
}


void processFEUAct(OSCMessage &msg, int addrOffset) {
  if(msg.match("/frown", addrOffset)) {
    if(msg.isFloat(0)) {
      Serial.print("FE - Frown: ");
    }
  } else if(msg.match("/surprise", addrOffset)) {
    Serial.print("FE - Surprise: ");
  }

  if(msg.isFloat(0)) {
    float value = msg.getFloat(0);
    Serial.println(value);
  }
}


void processFELAct(OSCMessage &msg, int addrOffset)
{
    if(msg.match("/Left", addrOffset))
    {
      digitalWrite(LED2, HIGH);
      Serial.print("FE - Left: ");
    }
    /*else if(msg.match("/Push", addrOffset))
    {
      digitalWrite(LED3, HIGH);
      Serial.print("FE - Push: ");
    }*/
    else if(msg.match("/smile", addrOffset))
    {
      digitalWrite(LED2, HIGH);
      delay(25);
      digitalWrite(LED2, LOW);
      Serial.print("FE - Smile: ");
    }
    else if(msg.match("/Furrow Brows", addrOffset))
    {
      digitalWrite(LED4, HIGH);
      delay(25);
      digitalWrite(LED4, LOW);
      Serial.print("FE - Furrow Brows: ");
    }
      else if(msg.match("/winkL", addrOffset)) {
    Serial.println("FE - Wink Left");
     digitalWrite(LED3, HIGH);
      delay(25);
      digitalWrite(LED3, LOW);
    }
  /*  else if(msg.match("/smirkLeft", addrOffset))
    {
      Serial.print("FE - Smirk Left: ");
    }
    else if(msg.match("/smirkRight", addrOffset))
    {
      Serial.print("FE - Smirk Right: ");
    }
*/
  if(msg.isFloat(0))
  {
    float value = msg.getFloat(0);
    Serial.println(value);
  }
}
/*
void processMC(OSCMessage &msg, int addrOffset) {
if(msg.match("/neutral", addrOffset)) {
Serial.print("MC - Neutral: ");
digitalWrite(LM1, LOW);
digitalWrite(LM2, LOW);
} else if(msg.match("/push", addrOffset)) {
Serial.print("MC - Push: ");
digitalWrite(LM1, HIGH);
} else if(msg.match("/pull", addrOffset)) {
Serial.print("MC - Pull: ");
digitalWrite(LM2, HIGH);
}
*/
void processMC(OSCMessage &msg, int addrOffset) {
  if(msg.match("/neutral", addrOffset)) {
    digitalWrite(LED1, HIGH);
     delay(25);
      digitalWrite(LED1, LOW);
    Serial.print("MC - Push: ");
  } else if(msg.match("/push", addrOffset)) {
    digitalWrite(LED4, HIGH);
     delay(25);
      digitalWrite(LED4, LOW);
    Serial.print("MC - Push: ");
  }
}
/* } else if(msg.match("/pull", addrOffset)) {
    Serial.print("MC - Pull: ");
  } else if(msg.match("/left", addrOffset)) {
  //  digitalWrite(LED2, HIGH);
    Serial.print("MC - Left: ");
  } else if(msg.match("/Smile", addrOffset)) {
    //digitalWrite(LED3, HIGH);
    Serial. print("MC - Right: ");

  else if(msg.match("/lift", addrOffset)) {

     digitalWrite(LED4, HIGH);
      delay(25);
      digitalWrite(LED4, LOW);
      Serial.print("MC - lift: ");
  }
}

 /* } else if(msg.match("/drop", addrOffset)) {
    Serial.print("MC - drop: ");
  } else if(msg.match("/rotateLeft", addrOffset)) {
    Serial.print("MC - rotateLeft: ");
  } else if(msg.match("/rotateRight", addrOffset)) {
    Serial.print("MC - rotateRight: ");
  } else if(msg.match("/rotateClockwise", addrOffset)) {
    Serial.print("MC - rotateClockwise: ");
  } else if(msg.match("/rotateCounterClockwise", addrOffset)) {
    Serial.print("MC - rotateCounterClockwise: ");
  } else if(msg.match("/rotateForwards", addrOffset)) {
    Serial.print("MC - rotateForwards: ");
  } else if(msg.match("/rotateReverse", addrOffset)) {
    Serial.print("MC - rotateReverse: ");
  } else if(msg.match("/disappear", addrOffset)) {
    Serial.print("MC - disappear: ");
  }

  if(msg.isFloat(0)) {
    float value = msg.getFloat(0);
    Serial.println(value);
  }
}
}
/*
void processPM(OSCMessage &msg, int addrOffset) {
  if(msg.match("/foc", addrOffset)) {
    Serial.print("PM - focus: ");
  } else if(msg.match("/int", addrOffset)) {
    Serial.print("PM - interest: ");
  } else if(msg.match("/rel", addrOffset)) {
    Serial.print("PM - relaxation: ");
  } else if(msg.match("/str", addrOffset)) {
    Serial.print("PM - stress: ");
  } else if(msg.match("/exc", addrOffset)) {
    Serial.print("PM - excitement: ");
  } else if(msg.match("/eng", addrOffset)) {
    Serial.print("PM - engagement: ");
  }
//  else if(msg.match("/cognitiveStress", addrOffset)) {
//    Serial.print("PM - cognitiveStress: ");
//  }
//  else if(msg.match("/visualAttention", addrOffset)) {
//    Serial.print("PM - visualAttention: ");
//  }
//  else if(msg.match("/auditoryAttention", addrOffset)) {
//    Serial.print("PM - auditoryAttention: ");
//  }

  if(msg.isFloat(0)) {
    float value = msg.getFloat(0);
    Serial.println(value);
  }
}*/
Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by Doody02** [comment]
Greetings @hoangphamemotiv 
these are the codes of wifi after editing so we change the ethernet to wifi .
![IP-WiFi](https://user-images.githubusercontent.com/34331105/122882840-43491800-d345-11eb-9b30-55aa4a8ec7b6.PNG)
#include <SPI.h>
#include <WiFi.h>
#include <WiFiUdp.h>
#include <OSCBundle.h>
#define LED1 2 //red
#define LED2 3 //red
#define LED3 4 //red
#define LED4 5 //green
#define LED5 6 //yellow
// you can find this written on the board of some Arduino Ethernets or shields
byte mac[] = { 0xDE, 0xAD, 0xBE, 0xEF, 0xFE, 0xED }; // NOTE: Alternatively, you can assign a fixed IP to configure your Ethernet shield.
byte ip[] = { 192, 168, 43, 233 };
int serverPort = 8500; // Emotiv BCI out port
//Create UDP message object
WiFiUDP Udp;
void setup(){
  Serial.begin(9600); //9600 for a "normal" Arduino board (Uno for example). 115200 for a Teensy ++2 
  Serial.println("Emotiv BCI OSC test");
  pinMode(LED1, OUTPUT);
  pinMode(LED2, OUTPUT);
  pinMode(LED3, OUTPUT);
  pinMode(LED4, OUTPUT);
  pinMode(LED5, OUTPUT);
  
  // start the Ethernet connection:
  // NOTE: Alternatively, you can assign a fixed IP to configure your Ethernet shield.
  WiFi.begin(mac, ip);
  if (WiFi.begin(mac) == 0) {
    Serial.println("Failed to configure Ethernet using DHCP");
    // no point in carrying on, so do nothing forevermore:
    while(true);
  } 
  // print your local IP address:
  Serial.print("Arduino IP address: ");
  for (byte thisByte = 1; thisByte < 4; thisByte++) {
    // print the value of each byte of the IP address:
    Serial.print(WiFi.localIP()[thisByte], DEC);
    Serial.print(".");
  }
  Serial.println();
  Udp.begin(serverPort);
}

void loop(){
  //process received data from Emotiv BCI
  OSCMsgReceive();
} 
void OSCMsgReceive() {
  int size = Udp.parsePacket();  
  if(size > 1) {    
    OSCBundle bundleIN;
    while(size--)
      bundleIN.fill(Udp.read());
      if(!bundleIN.hasError()){
        bundleIN.route("/fac/eyeAct", processFEEyeAct);  // Facial_Expressions
         bundleIN.route("/fac/uAct",   processFEUAct);    // Facial_Expressions
         bundleIN.route("/fac/lAct",   processFELAct);    // Facial_Expressions
        bundleIN.route("/com", processMC); // Mental_Commands
   //     bundleIN.route("/met", processPM); // Performance_Metrics
    }
  }
}
 void processFEEyeAct(OSCMessage &msg, int addrOffset) {
  if(msg.match("/lookL", addrOffset)) {
    Serial.println("FE - Look Left");
  } else if(msg.match("/lookR", addrOffset)) {
    Serial.println("FE - Look Right");
  } else if(msg.match("/blink", addrOffset)) {
    Serial.println("FE - Blink");
  } else if(msg.match("/winkL", addrOffset)) {
    Serial.println("FE - Wink Left");
     digitalWrite(LED4, HIGH);
      delay(25);
      digitalWrite(LED4, LOW);
  } else if(msg.match("/winkR", addrOffset)) {
    Serial.println("FE - Wink Right");
  }
}


void processFEUAct(OSCMessage &msg, int addrOffset) {
  if(msg.match("/frown", addrOffset)) {
    if(msg.isFloat(0)) {
      Serial.print("FE - Frown: ");
    }
  } else if(msg.match("/surprise", addrOffset)) {
    Serial.print("FE - Surprise: ");
  }

  if(msg.isFloat(0)) {
    float value = msg.getFloat(0);
    Serial.println(value);
  }
}


void processFELAct(OSCMessage &msg, int addrOffset)
{
    if(msg.match("/Left", addrOffset))
    {
      digitalWrite(LED2, HIGH);
      Serial.print("FE - Left: ");
    } 
    /*else if(msg.match("/Push", addrOffset))
    {
      digitalWrite(LED3, HIGH);
      Serial.print("FE - Push: ");
    }*/
    else if(msg.match("/smile", addrOffset))
    {
      digitalWrite(LED2, HIGH);
      delay(25);
      digitalWrite(LED2, LOW);
      Serial.print("FE - Smile: ");
    }
    else if(msg.match("/Furrow Brows", addrOffset))
    {
      digitalWrite(LED4, HIGH);
      delay(25);
      digitalWrite(LED4, LOW);
      Serial.print("FE - Furrow Brows: ");
    }
      else if(msg.match("/winkL", addrOffset)) {
    Serial.println("FE - Wink Left");
     digitalWrite(LED3, HIGH);
      delay(25);
      digitalWrite(LED3, LOW);
    }
  /*  else if(msg.match("/smirkLeft", addrOffset))
    {
      Serial.print("FE - Smirk Left: ");
    } 
    else if(msg.match("/smirkRight", addrOffset))
    {
      Serial.print("FE - Smirk Right: ");
    }
*/
  if(msg.isFloat(0))
  {
    float value = msg.getFloat(0);
    Serial.println(value);
  }
}
/*
void processMC(OSCMessage &msg, int addrOffset) {
if(msg.match("/neutral", addrOffset)) {
Serial.print("MC - Neutral: ");
digitalWrite(LM1, LOW);
digitalWrite(LM2, LOW);
} else if(msg.match("/push", addrOffset)) {
Serial.print("MC - Push: ");
digitalWrite(LM1, HIGH);
} else if(msg.match("/pull", addrOffset)) {
Serial.print("MC - Pull: ");
digitalWrite(LM2, HIGH);
}
*/
void processMC(OSCMessage &msg, int addrOffset) {  
  if(msg.match("/neutral", addrOffset)) {
    digitalWrite(LED1, HIGH);
     delay(25);
      digitalWrite(LED1, LOW);
    Serial.print("MC - Push: ");
  } else if(msg.match("/push", addrOffset)) {
    digitalWrite(LED4, HIGH);
     delay(25);
      digitalWrite(LED4, LOW);
    Serial.print("MC - Push: ");
  }
}
/* } else if(msg.match("/pull", addrOffset)) {
    Serial.print("MC - Pull: ");
  } else if(msg.match("/left", addrOffset)) {
  //  digitalWrite(LED2, HIGH);
    Serial.print("MC - Left: ");
  } else if(msg.match("/Smile", addrOffset)) {
    //digitalWrite(LED3, HIGH);
    Serial. print("MC - Right: ");
  
  else if(msg.match("/lift", addrOffset)) {
    
     digitalWrite(LED4, HIGH);
      delay(25);
      digitalWrite(LED4, LOW);
      Serial.print("MC - lift: ");
  }
}
  
 /* } else if(msg.match("/drop", addrOffset)) {
    Serial.print("MC - drop: ");
  } else if(msg.match("/rotateLeft", addrOffset)) {
    Serial.print("MC - rotateLeft: ");
  } else if(msg.match("/rotateRight", addrOffset)) {
    Serial.print("MC - rotateRight: ");
  } else if(msg.match("/rotateClockwise", addrOffset)) {
    Serial.print("MC - rotateClockwise: ");
  } else if(msg.match("/rotateCounterClockwise", addrOffset)) {
    Serial.print("MC - rotateCounterClockwise: ");
  } else if(msg.match("/rotateForwards", addrOffset)) {
    Serial.print("MC - rotateForwards: ");
  } else if(msg.match("/rotateReverse", addrOffset)) {
    Serial.print("MC - rotateReverse: ");
  } else if(msg.match("/disappear", addrOffset)) {
    Serial.print("MC - disappear: ");
  }

  if(msg.isFloat(0)) {
    float value = msg.getFloat(0);
    Serial.println(value);
  }
}
}
/*
void processPM(OSCMessage &msg, int addrOffset) {
  if(msg.match("/foc", addrOffset)) {
    Serial.print("PM - focus: ");
  } else if(msg.match("/int", addrOffset)) {
    Serial.print("PM - interest: ");
  } else if(msg.match("/rel", addrOffset)) {
    Serial.print("PM - relaxation: ");
  } else if(msg.match("/str", addrOffset)) {
    Serial.print("PM - stress: ");
  } else if(msg.match("/exc", addrOffset)) {
    Serial.print("PM - excitement: ");
  } else if(msg.match("/eng", addrOffset)) {
    Serial.print("PM - engagement: ");
  } 
//  else if(msg.match("/cognitiveStress", addrOffset)) {
//    Serial.print("PM - cognitiveStress: ");
//  }
//  else if(msg.match("/visualAttention", addrOffset)) {
//    Serial.print("PM - visualAttention: ");
//  } 
//  else if(msg.match("/auditoryAttention", addrOffset)) {
//    Serial.print("PM - auditoryAttention: ");
//  }

  if(msg.isFloat(0)) {
    float value = msg.getFloat(0);
    Serial.println(value);
  }
}*/

**Comment by hoangphamemotiv** [comment]
@Doody02 i have no an arduino here to check your code. but i think there are many examples in the internet for connect Arduino to Wifi and transmit data. 
from your code, can you check status of Wifi to see if it connected or not?
if ( WiFi.status() ==  WL_CONNECTED ) 
  {
    // WiFi is UP,  do what ever
     Serial.print(" wifi connected ");
     }

**Comment by Doody02** [comment]
@hoangphamemotiv I have added these codes under void set up 
// Connect to WiFi network
  Serial.println();
  Serial.println();
  Serial.print("Connecting to ");
  Serial.println(ssid);
  WiFi.begin(ssid, pass);

  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("");

  Serial.println("WiFi connected");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());

  Serial.println("Starting UDP");
  Udp.begin(localPort);
  Serial.print("Local port: ");


still got ip ; 0.0.0

if you can help me even if later i would be so grateful . 

am trying to use the same codes for raspberry pi maybe it easier there .

**Comment by MohaFathi** [comment]
Hello , I’m having a problem in the ethernet connection ( I’m using Ethernet shield connected to the arduino and i connect my laptop to router through wifi but it wouldn’t work !! It gives me the message “ Failed to configure Ethernet using DHCP “ in the serial monitor
