### ISSUE TITLE
BCI-OSC grayed out on mac + invalid IP address 

### ISSUE THREAD

**Issue by Zacharydpberry** [Emotiv/opensoundcontrol#8]
Hey everyone, 

I recently purchased a subscription for BCI-OSC. I got it sending OSC data of Facial expressions on a Windows PC at work. However, when I tried it on my Mac at home, under the connection header it said invalid IP address and everything was grayed out. I can't set the port, data stream or click the start button. I've attached some screenshots of what this looks like. I'm aware of the 3 device limit with a BCI-OSC subscription, but I only have the software installed on two machines. Please could someone help me fix this so I can start streaming OSC data from the Emotiv with my Mac. FYI I'm using EmotivBCI 3.1.3.212 and have an Emotiv Epoc +. 

Thanks,

Zak 

<img width="1440" alt="Screenshot 2022-01-14 at 15 23 21" src="https://user-images.githubusercontent.com/82658469/149540146-ceab3648-01c0-4422-bebb-f7322a7d1624.png">

**Comment by emoviet** [comment]
did you try to create a new preset by press + button on the top-right corner?
